modLoader="javafml"
loaderVersion="[32,)"

[[mods]]
modId="vanillaexcavators"
version="${file.jarVersion}"
displayName="Vanilla Excavators"
updateJSONURL="https://raw.githubusercontent.com/MelanX/vanilla-excavators/master/update/update.json"
authors="MelanX"
credits="Draylar made this mod for Fabric, this is just a fork for Forge."
icon="assets/vanillaexcavators/icon.png"
description='''
Adds a ton of new excavators to the game!
'''
[[dependencies.vanillaexcavators]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillaexcavators]]
    modId="morevanillalib"
    mandatory=true
    versionRange="[1.2.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillaexcavators]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"