modLoader="javafml"
loaderVersion="[33,)"
license="MIT License"

[[mods]]
modId="vanillaexcavators"
version="${file.jarVersion}"
displayName="Vanilla Excavators"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/vanillaexcavators.json"
authors="MelanX"
credits="Draylar made this mod for Fabric, this is just a fork for Forge."
icon="assets/vanillaexcavators/icon.png"
description='''
Adds a ton of new excavators to the game!
'''
[[dependencies.vanillaexcavators]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillaexcavators]]
    modId="morevanillalib"
    mandatory=true
    versionRange="[1.2.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillaexcavators]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"